pub struct ProcessAuditData {
    pub session_count: i32,
    pub total_interactions: i32,
    pub steering_ratio: f64,
    pub exploration_score: f64,
    pub test_behavior: String,
    pub error_fix_cycles: i32,
    pub red_flags: Vec<String>,
    pub prompt_specificity: f64,
    pub files_read: i32,
    pub files_written: i32,
}

pub fn format_process_audit(data: &ProcessAuditData) -> String {
    let mut md = String::new();

    md.push_str(&format!(
        "## AI Process Audit — {} session{}, {} interactions\n\n",
        data.session_count,
        if data.session_count != 1 { "s" } else { "" },
        data.total_interactions,
    ));

    // Steering
    let steering_pct = (data.steering_ratio * 100.0) as u32;
    let steering_label = if steering_pct >= 70 {
        "High"
    } else if steering_pct >= 40 {
        "Medium"
    } else {
        "Low"
    };
    md.push_str(&format!(
        "**Steering:** {} — {}% of interactions had specific human prompts\n",
        steering_label, steering_pct
    ));

    // Exploration
    md.push_str(&format!(
        "**Exploration:** {} files read before first edit\n",
        data.files_read
    ));

    // Testing
    let test_label = match data.test_behavior.as_str() {
        "tdd" => "TDD — tests written before code",
        "test_after" => "Tests written after code",
        "test_only" => "Tests run (no code changes)",
        "no_tests" => "No tests detected",
        _ => "Unknown",
    };
    md.push_str(&format!("**Testing:** {}\n", test_label));

    // Error-fix cycles
    let cycle_note = if data.error_fix_cycles <= 2 {
        "(normal)"
    } else {
        "(high — possible brute forcing)"
    };
    md.push_str(&format!(
        "**Iterations:** {} error-fix cycle{} {}\n",
        data.error_fix_cycles,
        if data.error_fix_cycles != 1 { "s" } else { "" },
        cycle_note
    ));

    // Red flags
    if data.red_flags.is_empty() {
        md.push_str("**Red flags:** None\n");
    } else {
        md.push_str("**Red flags:**\n");
        for flag in &data.red_flags {
            md.push_str(&format!("- {}\n", flag));
        }
    }

    md.push_str("\n---\n");
    md.push_str("<sub>Generated by [Sannai](https://github.com/MereWhiplash/sannai) — AI process audit</sub>\n");

    md
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_process_audit_comment() {
        let data = ProcessAuditData {
            session_count: 3,
            total_interactions: 47,
            steering_ratio: 0.72,
            exploration_score: 0.85,
            test_behavior: "test_after".to_string(),
            error_fix_cycles: 2,
            red_flags: vec![],
            prompt_specificity: 0.65,
            files_read: 12,
            files_written: 5,
        };
        let comment = format_process_audit(&data);
        assert!(comment.contains("AI Process Audit"));
        assert!(comment.contains("3 sessions"));
        assert!(comment.contains("47 interactions"));
        assert!(comment.contains("Steering"));
        assert!(comment.contains("72%"));
        assert!(comment.contains("12 files read"));
        assert!(comment.contains("Red flags:") && comment.contains("None"));
    }

    #[test]
    fn test_format_with_red_flags() {
        let data = ProcessAuditData {
            session_count: 1,
            total_interactions: 10,
            steering_ratio: 0.3,
            exploration_score: 0.1,
            test_behavior: "no_tests".to_string(),
            error_fix_cycles: 5,
            red_flags: vec![
                "Detected: force push".to_string(),
                "Detected: --no-verify".to_string(),
            ],
            prompt_specificity: 0.2,
            files_read: 1,
            files_written: 8,
        };
        let comment = format_process_audit(&data);
        assert!(comment.contains("force push"));
        assert!(comment.contains("--no-verify"));
        assert!(comment.contains("No tests"));
    }
}
