use crate::provenance::attribution::{AttributionType, DiffAttribution};
use crate::provenance::interaction::Interaction;
use crate::provenance::lineage::{FileLineage, FileOpType};

pub struct CommentData {
    pub sessions: Vec<SessionSummary>,
    pub attributions: Vec<DiffAttribution>,
    pub llm_summary: Option<String>,
}

pub struct SessionSummary {
    pub session_id: String,
    pub interactions: Vec<Interaction>,
    pub lineage: Vec<FileLineage>,
    pub duration: String,
}

pub fn format_comment(data: &CommentData) -> String {
    let mut md = String::new();

    // Header
    let total_interactions: usize = data.sessions.iter().map(|s| s.interactions.len()).sum();
    let total_sessions = data.sessions.len();

    md.push_str("## \u{1f50d} Sannai Code Provenance\n\n");
    md.push_str(&format!(
        "**{} AI session{}** contributed to this PR across **{} interaction{}**.\n\n",
        total_sessions,
        if total_sessions != 1 { "s" } else { "" },
        total_interactions,
        if total_interactions != 1 { "s" } else { "" },
    ));

    // LLM Summary
    if let Some(summary) = &data.llm_summary {
        md.push_str("### Summary\n\n");
        md.push_str(summary);
        md.push_str("\n\n");
    }

    // Per-session interaction tables
    for session in &data.sessions {
        let short_id = &session.session_id[..std::cmp::min(8, session.session_id.len())];
        md.push_str(&format!(
            "### Session: `{}` \u{2014} {} interaction{}, {}\n\n",
            short_id,
            session.interactions.len(),
            if session.interactions.len() != 1 {
                "s"
            } else {
                ""
            },
            session.duration,
        ));

        md.push_str("| # | Prompt | Files touched | Attribution |\n");
        md.push_str("|---|--------|--------------|-------------|\n");

        for interaction in &session.interactions {
            let prompt_preview = truncate_for_table(&interaction.prompt, 60);
            let files = format_files_touched(&session.lineage, &interaction.id);
            let attr = format_interaction_attribution(&data.attributions, &interaction.id);

            md.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                interaction.sequence, prompt_preview, files, attr,
            ));
        }
        md.push('\n');
    }

    // Diff Attribution table
    if !data.attributions.is_empty() {
        md.push_str("### Diff Attribution\n\n");
        md.push_str("| File | Lines | Source | Confidence |\n");
        md.push_str("|------|-------|--------|------------|\n");

        for attr in &data.attributions {
            let source = match &attr.interaction_id {
                Some(id) => {
                    let seq = id.rsplit('-').next().unwrap_or("?");
                    format!("Interaction #{}", seq)
                }
                None => "Manual".to_string(),
            };

            let icon = match attr.attribution_type {
                AttributionType::AiGenerated => "\u{1f916}",
                AttributionType::AiAssisted => "\u{1f9d1}\u{200d}\u{1f4bb}",
                AttributionType::Manual => "\u{270d}\u{fe0f}",
                AttributionType::Unknown => "\u{2753}",
            };

            let confidence = if attr.confidence > 0.0 {
                format!("{}%", (attr.confidence * 100.0) as u32)
            } else {
                "\u{2014}".to_string()
            };

            md.push_str(&format!(
                "| {} | {}-{} | {} {} | {} |\n",
                attr.file_path, attr.hunk_start, attr.hunk_end, icon, source, confidence,
            ));
        }
        md.push('\n');
    }

    // Footer
    md.push_str("---\n");
    md.push_str("<sub>Generated by [Sannai](https://github.com/AaronFR/sannai) \u{2014} code provenance for AI-assisted development</sub>\n");

    md
}

pub struct ProcessAuditData {
    pub session_count: i32,
    pub total_interactions: i32,
    pub steering_ratio: f64,
    pub exploration_score: f64,
    pub test_behavior: String,
    pub error_fix_cycles: i32,
    pub red_flags: Vec<String>,
    pub prompt_specificity: f64,
    pub files_read: i32,
    pub files_written: i32,
}

pub fn format_process_audit(data: &ProcessAuditData) -> String {
    let mut md = String::new();

    md.push_str(&format!(
        "## AI Process Audit — {} session{}, {} interactions\n\n",
        data.session_count,
        if data.session_count != 1 { "s" } else { "" },
        data.total_interactions,
    ));

    // Steering
    let steering_pct = (data.steering_ratio * 100.0) as u32;
    let steering_label = if steering_pct >= 70 {
        "High"
    } else if steering_pct >= 40 {
        "Medium"
    } else {
        "Low"
    };
    md.push_str(&format!(
        "**Steering:** {} — {}% of interactions had specific human prompts\n",
        steering_label, steering_pct
    ));

    // Exploration
    md.push_str(&format!(
        "**Exploration:** {} files read before first edit\n",
        data.files_read
    ));

    // Testing
    let test_label = match data.test_behavior.as_str() {
        "tdd" => "TDD — tests written before code",
        "test_after" => "Tests written after code",
        "test_only" => "Tests run (no code changes)",
        "no_tests" => "No tests detected",
        _ => "Unknown",
    };
    md.push_str(&format!("**Testing:** {}\n", test_label));

    // Error-fix cycles
    let cycle_note = if data.error_fix_cycles <= 2 {
        "(normal)"
    } else {
        "(high — possible brute forcing)"
    };
    md.push_str(&format!(
        "**Iterations:** {} error-fix cycle{} {}\n",
        data.error_fix_cycles,
        if data.error_fix_cycles != 1 { "s" } else { "" },
        cycle_note
    ));

    // Red flags
    if data.red_flags.is_empty() {
        md.push_str("**Red flags:** None\n");
    } else {
        md.push_str("**Red flags:**\n");
        for flag in &data.red_flags {
            md.push_str(&format!("- {}\n", flag));
        }
    }

    md.push_str("\n---\n");
    md.push_str("<sub>Generated by [Sannai](https://github.com/MereWhiplash/sannai) — AI process audit</sub>\n");

    md
}

fn truncate_for_table(text: &str, max_len: usize) -> String {
    let first_line = text.lines().next().unwrap_or("");
    // Escape pipes and newlines for markdown table cells
    let clean = first_line.replace('|', "\\|");
    if clean.chars().count() <= max_len {
        clean
    } else {
        let truncated: String = clean.chars().take(max_len).collect();
        format!("{}...", truncated)
    }
}

fn format_files_touched(lineage: &[FileLineage], interaction_id: &str) -> String {
    let files: Vec<String> = lineage
        .iter()
        .filter(|l| l.interaction_id == interaction_id)
        .map(|l| {
            let ops: Vec<&str> = l
                .operations
                .iter()
                .map(|op| match op.op_type {
                    FileOpType::Read => "R",
                    FileOpType::Write => "W",
                    FileOpType::ReadWrite => "RW",
                })
                .collect();
            let op_str = ops.join(",");
            let filename = l.file_path.rsplit('/').next().unwrap_or(&l.file_path);
            format!("{} ({})", filename, op_str)
        })
        .collect();

    if files.is_empty() {
        "\u{2014}".to_string()
    } else {
        files.join(", ")
    }
}

fn format_interaction_attribution(
    attributions: &[DiffAttribution],
    interaction_id: &str,
) -> String {
    let attrs: Vec<&DiffAttribution> = attributions
        .iter()
        .filter(|a| a.interaction_id.as_deref() == Some(interaction_id))
        .collect();

    if attrs.is_empty() {
        return "\u{2014}".to_string();
    }

    let best = attrs
        .iter()
        .max_by(|a, b| {
            a.confidence
                .partial_cmp(&b.confidence)
                .unwrap_or(std::cmp::Ordering::Equal)
        })
        .unwrap();

    let label = match best.attribution_type {
        AttributionType::AiGenerated => "\u{1f916} AI-generated",
        AttributionType::AiAssisted => "\u{1f9d1}\u{200d}\u{1f4bb} AI-assisted",
        AttributionType::Manual => "\u{270d}\u{fe0f} Manual",
        AttributionType::Unknown => "\u{2753} Unknown",
    };

    if best.confidence > 0.0 {
        format!("{} ({:.0}%)", label, best.confidence * 100.0)
    } else {
        label.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    #[test]
    fn test_format_empty_comment() {
        let data = CommentData {
            sessions: vec![],
            attributions: vec![],
            llm_summary: None,
        };
        let comment = format_comment(&data);
        assert!(comment.contains("Sannai Code Provenance"));
        assert!(comment.contains("0 AI sessions"));
    }

    #[test]
    fn test_format_with_session() {
        let now = Utc::now();
        let data = CommentData {
            sessions: vec![SessionSummary {
                session_id: "abcdef12-3456-7890".to_string(),
                interactions: vec![Interaction {
                    id: "abcdef12-1".to_string(),
                    session_id: "abcdef12".to_string(),
                    sequence: 1,
                    prompt: "Fix the upload bug".to_string(),
                    response_texts: vec!["I'll fix that.".to_string()],
                    tool_calls: vec![],
                    timestamp_start: now,
                    timestamp_end: now,
                }],
                lineage: vec![],
                duration: "5m".to_string(),
            }],
            attributions: vec![],
            llm_summary: None,
        };

        let comment = format_comment(&data);
        assert!(comment.contains("1 AI session"));
        assert!(comment.contains("abcdef12"));
        assert!(comment.contains("Fix the upload bug"));
    }

    #[test]
    fn test_format_with_summary() {
        let data = CommentData {
            sessions: vec![],
            attributions: vec![],
            llm_summary: Some("The developer built a feature.".to_string()),
        };
        let comment = format_comment(&data);
        assert!(comment.contains("### Summary"));
        assert!(comment.contains("The developer built a feature."));
    }

    #[test]
    fn test_truncate_for_table() {
        assert_eq!(truncate_for_table("short", 60), "short");
        let long = "a".repeat(100);
        let truncated = truncate_for_table(&long, 60);
        assert!(truncated.ends_with("..."));
        assert!(truncated.chars().count() <= 63); // 60 + "..."
    }

    #[test]
    fn test_truncate_for_table_multibyte_utf8() {
        // Should not panic on multi-byte characters
        let text = "\u{1f600}".repeat(100); // 100 emoji
        let truncated = truncate_for_table(&text, 10);
        assert!(truncated.ends_with("..."));
        assert!(truncated.chars().count() <= 13); // 10 + "..."
    }

    #[test]
    fn test_format_process_audit_comment() {
        let data = ProcessAuditData {
            session_count: 3,
            total_interactions: 47,
            steering_ratio: 0.72,
            exploration_score: 0.85,
            test_behavior: "test_after".to_string(),
            error_fix_cycles: 2,
            red_flags: vec![],
            prompt_specificity: 0.65,
            files_read: 12,
            files_written: 5,
        };
        let comment = format_process_audit(&data);
        assert!(comment.contains("AI Process Audit"));
        assert!(comment.contains("3 sessions"));
        assert!(comment.contains("47 interactions"));
        assert!(comment.contains("Steering"));
        assert!(comment.contains("72%"));
        assert!(comment.contains("12 files read"));
        assert!(comment.contains("Red flags:") && comment.contains("None"));
    }

    #[test]
    fn test_format_with_red_flags() {
        let data = ProcessAuditData {
            session_count: 1,
            total_interactions: 10,
            steering_ratio: 0.3,
            exploration_score: 0.1,
            test_behavior: "no_tests".to_string(),
            error_fix_cycles: 5,
            red_flags: vec![
                "Detected: force push".to_string(),
                "Detected: --no-verify".to_string(),
            ],
            prompt_specificity: 0.2,
            files_read: 1,
            files_written: 8,
        };
        let comment = format_process_audit(&data);
        assert!(comment.contains("force push"));
        assert!(comment.contains("--no-verify"));
        assert!(comment.contains("No tests"));
    }
}
